# Generated by Django 5.2.6 on 2025-12-19 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_jogo', models.JSONField(default=dict)),
                ('rodada_atual', models.IntegerField(default=1)),
                ('valor_de_mercado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_atualizacao'],
            },
        ),
    ]
